### ISSUE TITLE
Code migration to .NET Core 3.1 

### ISSUE THREAD

**Issue by mukhtarhussain** [kawansoft/AceQL.Client#17]
Hi Nicolas,

I am using AceQL.Client package in my .NET Core 3.1 project, but see the below warning:

**Package 'AceQL.Client 5.5.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.**

And when I ran the program, I got the following error:

![image](https://user-images.githubusercontent.com/65705142/98783498-86ade080-245e-11eb-9f0a-fe473029ab8d.png)

Are there any plans to migrate the code to .NET Core 3.1?

**Comment by ndepomereu** [comment]
Hi Mukhtar,
Yes, we will migrate our PCL Library to .NET Standard and will support .NET Core. This must be done.
But I don't have a precise schedule for that, should be asap in the next 2 weeks, depending on technical problems encountered with third-party libraries.

**Comment by mukhtarhussain** [comment]
Great!! Thanks Nicolas.

**Comment by ndepomereu** [comment]
Hi Mukhtar,

The AceQL.Client package is now a .Net Standard 2.0 library. 
The Nuget package to use is 6.0.0: https://www.nuget.org/packages/AceQL.Client/6.0.0

Regards,
Nicolas

P.S: 
1) Because of Git issues with Visual Studio, please go to the new GitHub project https://github.com/kawansoft/AceQL.Client2 for everything concerning source code and user documentation.
2) The previous 5.5.0 version packaged as a Portable Class Library is still accessible on NuGet: https://www.nuget.org/packages/AceQL.Client/5.5.0

**Comment by mukhtarhussain** [comment]
Awesome. Thanks Nicolas for your prompt action.

Cheers,
Mukhtar
