### ISSUE TITLE
Could not execute insert statement for DateTime.UtcNow

### ISSUE THREAD

**Issue by quirrel1002** [kawansoft/AceQL.Client#2]
hello,
I found an issue with Inserting DateTime "objects" through AceQL into database.

If I execute e.g:
`string sql = "INSERT INTO dbo.Table (PackageId, Version, CreationDate) " +
                                "VALUES (@PackageId, @CreationDate) " +
                                "RETURNING Id";
AceQLCommand command = new AceQLCommand(sql, connection);
command.Parameters.AddWithValue("@PackageId", 12345);
command.Parameters.AddWithValue("@Version", "1.2.3.5");
command.Parameters.AddWithValue("@CreationDate", DateTime.UtcNow);
AceQLDataReader dataReader = await command.ExecuteReaderAsync();`

I get the following error in one of my machines:

"Could not execute insert statement:
 ErrorType: 2 / reason: For input string "1591621302745.55" / httpStatusCode: BadRequest
"
While it works on others. 
It works on all of my machines when I change 
`command.Parameters.AddWithValue("@CreationDate", DateTime.UtcNow);`
to 
`command.Parameters.AddWithValue("@CreationDate", DateTime.Today);`
So I suspect some formatting/convertsion issue depending on locale/regional settings off windows/.Net?
Any hint is highly appreciated.

**Comment by ndepomereu** [comment]
Hi,
There are no differences between the first and second occurrence of your 2 sample lines:
command.Parameters.AddWithValue("@CreationDate", DateTime.UtcNow);

**Comment by quirrel1002** [comment]
Sorry for that, I corrected the initial post

**Comment by ndepomereu** [comment]
Ok, the problem is due to a missed truncation.
We convert DateTime.Now or DateTime.UtcNow to a UNIX  date/time in milliseconds.
But the computation leaves a fractional value after comma (",") on some locales like mine in France and a dot (".") on other locales like yours.
We remove everything after the comma but forgot to it too after the dot for users in this kind of locale.
In your case, because numbers after the dot were not removed, the value "1591621302745.55" could not be inserted.
I will build a new version.

**Comment by ndepomereu** [comment]
Hi,
DateTime.UtcNow problem is fixed in new version 4.2.2.

**Comment by quirrel1002** [comment]
hello,
I checked also on my side it worked as expected now. thanks for quick response and support
